version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysqlserver
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: project_react
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - .docker/project_react.sql:/docker-entrypoint-initdb.d/project_react.sql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
      - backend
  
  backend-api:
    build: ./backend
    container_name: backend-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 4000:4000
    environment:
      - DB_HOST=172.20.0.2
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=project_react
      - DB_PORT=3306
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    networks:
      - backend
      - frontend

  frontend-ui:
    container_name: frontend-ui
    build:
      context: ./frontend
      args:
        - REACT_APP_API_BASE_URL=http://152.67.111.54:4000
    ports:
      - 8888:80
    depends_on:
      - backend-api
    networks:
      - frontend  

volumes: 
  db:

networks:
  backend:
    name: backend-network
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
  frontend:
    name: frontend-network