version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysqlserver
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_HOST:'%'
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - .docker/project_react.sql:/docker-entrypoint-initdb.d/project_react.sql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
      - backend
  
  backend-api:
    image: riqi/backend-api:latest
    container_name: backend-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=172.20.0.2
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    networks:
      - backend
      - frontend

  frontend-ui:
    container_name: frontend-ui
    image: riqi/react-web:latest
    environment:
      - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    depends_on:
      - backend-api
    networks:
      - frontend  

volumes: 
  db:

networks:
  backend:
    name: backend-network
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
  frontend:
    name: frontend-network